version: '3.8'
services:
  web:
    container_name: 'web'
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    command: bash -c "uvicorn main:app --reload --host 127.0.0.1 --port 8000"

  nginx:
    container_name: 'nginx'
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  db:
    container_name: 'db'
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
